name: Release
on: [workflow_dispatch]

permissions:
  contents: write

env:
  MINECRAFT_VERSION: 1.19.2
  JAVA_VERSION: 17
  VERSION: 1.2.0
  CREATE_VERSION: 0.5.0.i

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

      - name: Publish (CurseForge/Modrinth)
        uses: Kir-Antipov/mc-publish@v3.1
        with:
          # Modrinth
          modrinth-id: JWGBpFUP
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          # CurseForge
          curseforge-id: 688768
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          # Config
          name: "CEI ${{ env.VERSION }} for Create ${{ env.MINECRAFT_VERSION }}-${{ env.CREATE_VERSION }}"
          version: ${{ env.VERSION }}
          version-type: release
          changelog-file: changelog/${{ env.VERSION }}.md
          files-primary: build/libs/*-${{ env.VERSION }}!(-@(dev|sources|slim)).jar
          files-secondary: ""

          loaders: |
            forge
          game-versions: |
            ${{ env.MINECRAFT_VERSION }}
          dependencies: |
            create | depends | *
          java: |
            ${{ env.JAVA_VERSION }}
          retry-attempts: 2
          retry-delay: 10000
